CREATE TABLE Worker (
  WORKER_ID INTEGER auto_increment PRIMARY KEY,
  FIRST_NAME VARCHAR(25) NOT NULL,
  LAST_NAME VARCHAR(25) NOT NULL,
  SALARY int CHECK( SALARY BETWEEN 10000 AND 25000),
  JOINING_DATE DATETIME,
  dept TEXT NOT NULL check (dept IN ('HR', 'Sales','Accts','IT'))
);

Insert into Worker Values(1,'ajay','verma',12000,'2024-03-23','HR');
INSERT INTO Worker (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, dept) VALUES ('no','one', 20000, '2016-06-11', 'Accts');
INSERT INTO Worker (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, dept) VALUES ('Swayam', 'gupta', 20000, '2016-06-11', 'Sales');
INSERT INTO Worker (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, dept) VALUES ('Aniket', 'gupta', 20000, '2016-06-11', 'Sales');
INSERT INTO Worker (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, dept) VALUES ('Ramit', 'gupta', 20000, '2016-06-11', 'Sales');
INSERT INTO Worker (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, dept) VALUES ('Gulfam', 'Ansari', 20000, '2016-06-11', 'Sales');
Insert INTO Worker (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, dept) VALUES ('Sahil', 'Garg', 21000, '2020-01-05', 'IT');


select FIRST_NAME as WOKER_NAME from Worker;
select UPPER(FIRST_NAME) from Worker;
SELECT DISTINCT dept FROM Worker;
SELECT SUBSTRING(FIRST_NAME,1,3) FROM Worker;
SELECT INSTR(FIRST_NAME,'a') FROM Worker WHERE FIRST_NAME='Aniket';
SELECT RTRIM(FIRST_NAME) FROM Worker;
SELECT LTRIM(dept) FROM Worker;
SELECT DISTINCT dept, LENGTH(dept) FROM Worker;
SELECT REPLACE(FIRST_NAME,'a','A') FROM Worker;
SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS COMPLETE_NAME FROM Worker;
SELECT * FROM Worker ORDER BY FIRST_NAME ASC;
SELECT * FROM Worker ORDER BY FIRST_NAME ASC,dept desc;  -- wonr work for desc because my data is different applied--
SELECT * FROM Worker WHERE FIRST_NAME IN ('swayam','aniket');
SELECT * FROM Worker WHERE FIRST_NAME NOT IN ('ramit','gulfam');
SELECT * FROM Worker WHERE dept='Admin';
SELECT * FROM Worker WHERE FIRST_NAME LIKE '%a%';
INSERT INTO Worker (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, dept) VALUES ('Riya', 'Mishra', 21100, '2014-02-01', 'HR');
SELECT * FROM Worker WHERE FIRST_NAME LIKE '%a';
INSERT INTO Worker (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, dept) VALUES ('Ramesh', 'Agarwal', 11100, '2014-02-01', 'Accts');
SELECT * FROM Worker WHERE FIRST_NAME LIKE '_____h';
SELECT * FROM Worker WHERE SALARY BETWEEN 10000 AND 50000;
SELECT * FROM Worker WHERE YEAR(JOINING_DATE)=2014 AND MONTH(JOINING_DATE)=2;
SELECT COUNT(*) AS TOTAL_EMPLOYEES FROM Worker WHERE dept='HR';
select * from Worker;