Create database Assignment;
use Assignment;
CREATE TABLE Employee (
    EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(25) NOT NULL,
    EXP INT CHECK (EXP >= 2),
    SALARY INT CHECK (SALARY BETWEEN 12000 AND 30000),
    DEPARTMENT_NAME VARCHAR(20)
    CHECK (DEPARTMENT_NAME IN ('HR','Sales','Accts','IT')),
    MANAGER_NAME VARCHAR(25)
);
INSERT INTO Employee
(NAME, EXP, SALARY, DEPARTMENT_NAME, MANAGER_NAME)
VALUES
('Swayam', 3, 20000, 'Sales', 'Aswin'),
('Aniket', 4, 22000, 'IT', 'Puneet'),
('Ramit', 5, 21000, 'HR', 'Aswin'),
('Gulfam', 6, 25000, 'Accts', 'Puneet'),
('Sahil', 3, 23000, 'IT', 'Aswin');


SELECT EMPLOYEE_ID, NAME, SALARY FROM Employee;
SELECT EMPLOYEE_ID AS 'Employee ID', NAME AS 'Name of Employee', SALARY AS 'Salary of Employee' FROM Employee;
SELECT NAME, SALARY, SALARY + 2000 AS INCREMENTED_SALARY FROM Employee;
SELECT DEPARTMENT_NAME, SUM(SALARY) AS TOTAL_SALARY FROM Employee GROUP BY DEPARTMENT_NAME;
SELECT DEPARTMENT_NAME, SUM(SALARY) AS TOTAL_SALARY, MAX(SALARY) AS MAX_SALARY, AVG(SALARY) AS AVG_SALARY FROM Employee GROUP BY DEPARTMENT_NAME;
SELECT * FROM Employee ORDER BY SALARY DESC;
SELECT ROW_NUMBER() OVER() AS SEQ_NO, NAME FROM Employee;
SELECT NAME, SALARY, RANK() OVER(ORDER BY SALARY DESC) AS RANKING FROM Employee;
ALTER TABLE Employee ADD AGE INT;
ALTER TABLE Employee MODIFY AGE INT DEFAULT 26 CHECK (AGE BETWEEN 26 AND 60);
UPDATE Employee SET AGE = 26 WHERE AGE IS NULL;
SELECT COUNT(DISTINCT DEPARTMENT_NAME) FROM Employee;
SELECT UPPER(NAME) from Employee;
SELECT SUBSTRING(NAME,1,4) FROM Employee;
SELECT NAME, INSTR(NAME,'a') FROM Employee;
SELECT DEPARTMENT_NAME, COUNT(*) AS TOTAL_EMPLOYEES FROM Employee GROUP BY DEPARTMENT_NAME;
SELECT MANAGER_NAME, COUNT(*) AS TOTAL_EMPLOYEES FROM Employee GROUP BY MANAGER_NAME;
SELECT * FROM Employee WHERE EMPLOYEE_ID IN (101,102,110);
SELECT * FROM Employee WHERE EMPLOYEE_ID BETWEEN 100 AND 101;
SELECT * FROM Employee WHERE DEPARTMENT_NAME='HR';
SELECT * FROM Employee WHERE DEPARTMENT_NAME IN ('HR','Accts');
SELECT * FROM Employee WHERE NAME LIKE 'A%';
SELECT * FROM Employee WHERE NAME LIKE '%a%';
SELECT DEPARTMENT_NAME, AVG(SALARY) FROM Employee GROUP BY DEPARTMENT_NAME HAVING AVG(SALARY) < 12000;
SELECT * FROM Employee WHERE DEPARTMENT_NAME != 'Accts' AND SALARY NOT BETWEEN 10000 AND 20000;